### ISSUE TITLE
更新后启动报错

### ISSUE THREAD

**Issue by Kiana1314** [noneplugin/nonebot-plugin-boardgame#18]
10-24 14:09:12 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_orm"
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(id, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(game_id, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(session_id, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(name, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(start_time, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(update_time, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(player_black_id, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(player_black_name, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(player_white_id, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(player_white_name, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(positions, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) _configure_property(is_game_over, Column)
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) Identified primary key columns: OrderedSet([Column('id', Integer(), table=<nonebot_plugin_boardgame_gamerecord>, primary_key=True, nullable=False)])
2023-10-24 14:09:12 INFO (GameRecord|nonebot_plugin_boardgame_gamerecord) constructed
10-24 14:09:13 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_boardgame" from "nonebot-plugin-boardgame.nonebot_plugin_boardgame"
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(id, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(game_id, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(session_id, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(start_time, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(update_time, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_red_id, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_red_name, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_red_is_ai, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_red_level, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_black_id, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_black_name, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_black_is_ai, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(player_black_level, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(start_fen, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(moves, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) _configure_property(is_game_over, Column)
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) Identified primary key columns: OrderedSet([Column('id', Integer(), table=<nonebot_plugin_cchess_gamerecord>, primary_key=True, nullable=False)])
2023-10-24 14:09:13 INFO (GameRecord|nonebot_plugin_cchess_gamerecord) constructed
10-24 14:09:14 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_cchess" from "nonebot-plugin-cchess.nonebot_plugin_cchess"
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(id, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(game_id, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(session_id, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(start_time, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(update_time, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_white_id, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_white_name, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_white_is_ai, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_white_level, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_black_id, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_black_name, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_black_is_ai, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(player_black_level, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(start_fen, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(moves, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) _configure_property(is_game_over, Column)
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) Identified primary key columns: OrderedSet([Column('id', Integer(), table=<nonebot_plugin_chess_gamerecord>, primary_key=True, nullable=False)])
2023-10-24 14:09:14 INFO (GameRecord|nonebot_plugin_chess_gamerecord) constructed
10-24 14:09:15 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_chess" from "nonebot-plugin-chess.nonebot_pl
ugin_chess"

10-24 14:09:20 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) _configure_property(id, Column)
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) _configure_property(user_id, Column)
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) _configure_property(user_name, Column)
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) _configure_property(content, Column)
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) _configure_property(time, Column)
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) _configure_property(bottle_id, Column)
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) Identified primary key columns: OrderedSet([Column('id', Integer(), table=<nonebot_plugin_bottle_comment>, primary_key=True, nullable=False)])
2023-10-24 14:09:20 INFO (Comment|nonebot_plugin_bottle_comment) constructed
2023-10-24 14:09:20 INFO (Like|nonebot_plugin_bottle_like) _configure_property(id, Column)
2023-10-24 14:09:20 INFO (Like|nonebot_plugin_bottle_like) _configure_property(user_id, Column)
2023-10-24 14:09:20 INFO (Like|nonebot_plugin_bottle_like) _configure_property(bottle_id, Column)
2023-10-24 14:09:20 INFO (Like|nonebot_plugin_bottle_like) Identified primary key columns: OrderedSet([Column('id', Integer(), table=<nonebot_plugin_bottle_like>, primary_key=True, nullable=False)])
2023-10-24 14:09:20 INFO (Like|nonebot_plugin_bottle_like) constructed
2023-10-24 14:09:20 INFO (Report|nonebot_plugin_bottle_report) _configure_property(id, Column)
2023-10-24 14:09:20 INFO (Report|nonebot_plugin_bottle_report) _configure_property(user_id, Column)
2023-10-24 14:09:20 INFO (Report|nonebot_plugin_bottle_report) _configure_property(bottle_id, Column)
2023-10-24 14:09:20 INFO (Report|nonebot_plugin_bottle_report) Identified primary key columns: OrderedSet([Column('id', Integer(), table=<nonebot_plugin_bottle_report>, primary_key=True, nullable=False)])
2023-10-24 14:09:20 INFO (Report|nonebot_plugin_bottle_report) constructed
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(id, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(user_id, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(group_id, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(user_name, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(group_name, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(content, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(report, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(like, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(picked, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(is_del, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) _configure_property(time, Column)
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) Identified primary key columns: OrderedSet([Column('id', Integer(), table=<nonebot_plugin_bottle_bottle>, primary_key=True, nullable=False)])
2023-10-24 14:09:20 INFO (Bottle|nonebot_plugin_bottle_bottle) constructed
10-24 14:09:21 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_bottle" from "nonebot_plugin_bottle.nonebot_plugin_bottle"
10-24 14:09:21 [SUCCESS] nonebot | Running NoneBot...

2023-10-24 14:09:23 INFO Context impl SQLiteImpl.
2023-10-24 14:09:23 INFO Will assume non-transactional DDL.
10-24 14:09:23 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\bot\NB2\venv\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 36, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 30, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\__init__.py", line 91, in init_orm
    await greenlet_spawn(migrate.check, alembic_config)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\migrate.py", line 500, in check
    script_directory.run_env()
  File "D:\bot\NB2\venv\lib\site-packages\alembic\script\base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "D:\bot\NB2\venv\lib\site-packages\alembic\util\pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "D:\bot\NB2\venv\lib\site-packages\alembic\util\pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 69, in <module>
    await_fallback(run_migrations_online())
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 152, in await_fallback
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 63, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 886, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 54, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "D:\bot\NB2\venv\lib\site-packages\alembic\runtime\environment.py", line 937, in run_migrations
    self.get_context().run_migrations(**kw)
  File "D:\bot\NB2\venv\lib\site-packages\alembic\runtime\migration.py", line 612, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\migrate.py", line 488, in retrieve_migrations
    raise click.UsageError("目标数据库未更新到最新修订")
click.exceptions.UsageError: 目标数据库未更新到最新修订

2023-10-24 14:09:23 ERROR Traceback (most recent call last):
  File "D:\bot\NB2\venv\lib\site-packages\starlette\routing.py", line 677, in lifespan
  File "C:\Users\clb\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in _lifespan_manager
    await self._lifespan.startup()
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 36, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot\drivers\_lifespan.py", line 30, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\__init__.py", line 91, in init_orm
    await greenlet_spawn(migrate.check, alembic_config)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 190, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\migrate.py", line 500, in check
    script_directory.run_env()
  File "D:\bot\NB2\venv\lib\site-packages\alembic\script\base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "D:\bot\NB2\venv\lib\site-packages\alembic\util\pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "D:\bot\NB2\venv\lib\site-packages\alembic\util\pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 69, in <module>
    await_fallback(run_migrations_online())
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 152, in await_fallback
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 63, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 886, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
  File "D:\bot\NB2\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 54, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "D:\bot\NB2\venv\lib\site-packages\alembic\runtime\environment.py", line 937, in run_migrations
    self.get_context().run_migrations(**kw)
  File "D:\bot\NB2\venv\lib\site-packages\alembic\runtime\migration.py", line 612, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "D:\bot\NB2\venv\lib\site-packages\nonebot_plugin_orm\migrate.py", line 488, in retrieve_migrations
    raise click.UsageError("目标数据库未更新到最新修订")
click.exceptions.UsageError: 目标数据库未更新到最新修订

10-24 14:09:23 [ERROR] uvicorn | Application startup failed. Exiting.
2023-10-24 14:09:23 ERROR Application startup failed. Exiting.

**Comment by MeetWq** [comment]
运行 `nb orm upgrade`
