### ISSUE TITLE
关于nonebot_plugin_alconna插件的错误

### ISSUE THREAD

**Issue by LuckySJTU** [noneplugin/nonebot-plugin-boardgame#20]
在更新到0.4.0版本之后，插件初始化时报错，错误信息如下：
```bash
Traceback (most recent call last):
  ......
  File "C:\Users\users\.conda\envs\bot\lib\site-packages\nonebot_plugin_boardgame\__init__.py", line 76, in <module>
    Alconna(
  File "C:\Users\users\.conda\envs\bot\lib\site-packages\arclet\alconna\core.py", line 170, in __init__
    command_manager.register(self)
  File "C:\Users\users\.conda\envs\bot\lib\site-packages\arclet\alconna\manager.py", line 116, in register
    argv = self.__argv[command] = __argv_type__.get()(command.meta, command.namespace_config, command.separators)  # type: ignore
  File "<string>", line 14, in __init__
TypeError: MessageArgv.__post_init__() takes 1 positional argument but 2 were given
```

我尝试将`nonebot_plugin_alconna`升级到最新版本，但是仍无法解决问题。
或许应该回退一个版本？

**Comment by MeetWq** [comment]
等 `nonebot-plugin-alconna` 更新，或者暂时降级 `arclet-alconna`

```
pip install --force-reinstall arclet-alconna=="1.8.3"
```

**Comment by LuckySJTU** [comment]
感谢，问题解决了！
